#!/usr/bin/env python3
import argparse
import logging
import os
import time

from kafka import KafkaProducer

logger = logging.getLogger('uptime.producer')


def on_send_error():
    logger.error('Faild to send data')


def run():
    logger.info('Creating a producer')
    producer = KafkaProducer(bootstrap_servers=config.kafka_url,
                             client_id=config.client_id,
                             security_protocol='SSL' if config.ca and config.cert and config.key else 'PLAINTEXT',
                             ssl_cafile=config.ca,
                             ssl_certfile=config.cert,
                             ssl_keyfile=config.key,
                             value_serializer=lambda x: x.encode('utf-8'))

    while True:
        try:
            with open('/proc/uptime', 'r') as uptime:
                message = uptime.readline().split()[0]

            logger.info('Sending: {}'.format(message))
            producer.send(config.topic, message).add_errback(on_send_error)

            time.sleep(2)
        except Exception:  # Assuming exception is raised when we want to exit the script
            logger.info('Flushing Producer')
            producer.flush()


if __name__ == '__main__':
    logging.basicConfig(
        level=logging.INFO, format='[%(asctime)s] %(levelname)s %(name)s %(message)s')

    parser = argparse.ArgumentParser()

    parser.add_argument('--cert', dest='cert', metavar='CERT', default=os.environ.get('KAFKA_CERT'),
                        help='ssl certificate')
    parser.add_argument('--key', dest='key', metavar='KEY', default=os.environ.get('KAFKA_KEY'),
                        help='ssl certificate key')
    parser.add_argument('--ca', dest='ca', metavar='CA', default=os.environ.get('KAFKA_CA'),
                        help='ssl certificate root ca')
    parser.add_argument('-c', '--client-id', dest='client_id', metavar='CLIENT_ID',
                        default=os.environ.get('KAFKA_CLIENT_ID'), help='identify this client with kafka server')
    parser.add_argument('-t', '--topic', dest='topic', metavar='TOPIC', default=os.environ.get('KAFKA_TOPIC'),
                        help='kafka topic to send data to')
    parser.add_argument('-k', '--kafka', dest='kafka_url', metavar='KAFKA_URL', nargs='+',
                        default=[os.environ.get('KAFKA_URL')], help='kafka server URL')

    config = parser.parse_args()
    run()
